# Default values for helm-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: codayblue/busybox-web-demo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: "1.31.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {
    "ingress.kubernetes.io/ssl-redirect": "false"
  }
  hosts:
    - host: helm-demo.local
      paths: ["/"]
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
